<MyLayout>
    BoxLayout:
        orientation:"vertical"
        size:root.width,root.height

        padding:50
        spacing:20
        Button:
            text:"Hello, world!"

        Button:
            text:"Goodbye world!"    
        
        Button:
            text:"I am hungry"
            pos_hint:{'center_x':0.5}    
            #size_hint:(None,None)# in this case the item size not change 
            size_hint:(0.2,1)
            # width:200
            # height:50