<MyLayout>
    BoxLayout:
        orientation:"vertical"
        size:root.width,root.height



        Label:
            id:my_label
            text:'0% Progress'
            font_size: 32

        ProgressBar:
            id:my_progressbar
            #set default value
            #value:.25
            max:1
            min:0

            pos_hint: {'x': .1}
            size_hint_x:.8

        Button:
            text: "Press Me!"
            on_press: root.press_it()