<MyLayout>
	BoxLayout:
		orientation: "vertical"
		size: root.width, root.height
    
        Splitter:
            sizable_from:'bottom'
            Button:
                text: 'Hello world 1'
                font_size: 32

        Label:
            text:'this is some text!'
            font_size: 32

        Splitter:
            sizable_from:'top'
            Button:
                text: 'Hello world 2'
                font_size: 32